spring:
  datasource:
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
logging:
  level:
    ru.nataliaoskina: debug