--liquibase formatted sql

--changeset Anton:1
CREATE TABLE content
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    data TEXT        NOT NULL
);

CREATE TABLE node
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(150) NOT NULL,
    content_id BIGINT REFERENCES content (id)
);

CREATE TABLE edge_delay
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR(50) NOT NULL,
    previous_node_id BIGINT REFERENCES node (id),
    next_node_id     BIGINT REFERENCES node (id),
    delay            INTEGER     NOT NULL
);

CREATE TABLE edge_button
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR(50) NOT NULL,
    previous_node_id BIGINT REFERENCES node (id),
    next_node_id     BIGINT REFERENCES node (id),
    name             VARCHAR(50) NOT NULL
);

CREATE TABLE bot_user
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat            BIGINT NOT NULL,
    current_node_id BIGINT REFERENCES node (id)
);
